config/routes.rb
Rails.application.routes.draw do
  root "quotes#index"

  get '/about', to: 'quotes#about'
  get '/home', to: 'quotes#home'

  resources :quotes
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/quote.rb
class Quote < ApplicationRecord
    validates :title, presence: true
    validates :body, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/quotes_controller.rb
class QuotesController < ApplicationController
  before_action :set_quote, only: [:show, :edit, :update, :destroy]
  
  def index
    @quote = Quote.all
  end

  def show
  end

  def new
    @quote = Quote.new
  end

  def create
    @quote = Quote.new(quote_params)

    if @quote.save
      redirect_to quotes_path, notice: "Quote was successfully created."
    else
      render :new, status: :unprocessable_entity
    end
  end

  def edit
  end

  def update
    @quote = Quote.find(params[:id])
  
    if @quote.nil?
      redirect_to quotes_path, alert: "Quote not found."
    elsif @quote.update(quote_params)
      redirect_to quotes_path, notice: "Quote was successfully updated."
    else
      render :edit, status: :unprocessable_entity
    end
  end

  def destroy
    @quote = Quote.find(params[:id])
    @quote.destroy
    redirect_to quotes_path, notice: "Quote was successfully deleted!"
  end  

  private

  def set_quote
    @quote = Quote.find(params[:id])
  end

  def quote_params
    params.require(:quote).permit(:title, :body)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/quotes_helper.rb
module QuotesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>QuoteEditor</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-rbsA2VBKQhggwzxH7pPCaAqO46MgnOM80zW1RWuH61DGLwZJEdK2Kadq2F9CUG65" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-kenU1KFdBIe4zVF0s0G1M5b4hcpxyD9F7jL+jjXkk+Q2h455rYXK/7HAuoJl+0I4" crossorigin="anonymous"></script>
    
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= render "shared/navbar" %>

    <main class="container">
      <%= yield %>
      <%= render "shared/flash" %>
    </main>
  </body>
</html>

app/views/quotes/about.html.erb
<h2>About Us</h2>

app/views/quotes/edit.html.erb
<main class="container">
  <%= link_to sanitize("&larr; Back to quote"), quote_path %>

  <header class="header">
    <h1>Edit quote</h1>
  </header>

  <%= render "shared/form", quote: @quote %>
</main>

app/views/quotes/home.html.erb
<main class="">
    <h2>Welcome to Dev Quotes Share!</h2>
</main>

app/views/quotes/index.html.erb
<main class="container">
  <header class="header display-flex">
    <h1>Quotes</h1>
  <%= link_to "New Quote", new_quote_path, class: 'btn btn--primary' %>
  </header>
  <section>
    <ol class="list-group list-group-numbered">
      <% @quote.each do |quote| %>
        <li class="list-group-item">
          <%= link_to quote.title, quote %>
        </li>
      <% end %>
    </ol>
  </section>
</main>

app/views/quotes/new.html.erb
<main class="container">
  <%= link_to sanitize("&larr; Back to quotes"), quotes_path %>

  <header class="header">
    <h1>New quote</h1>
  </header>

  <%= render "shared/form", quote: @quote %>
</main>

app/views/quotes/show.html.erb
<main class="container">
  <header class="header">
    <%= link_to sanitize("&larr; Back to quotes"), quotes_path, class: "btn btn-primary mb-3" %>
  </header>
  <section>
    <h1>
      <%= @quote.title %>
    </h1>
    <p><%= @quote.body %></p>
    <ul>
      <li><%= link_to "Edit", edit_quote_path(@quote), class: "btn btn-secondary me-2" %></li>
      <li>
        <%= link_to "Delete", quote_path(@quote), method: :delete, data: {
              confirm: "Are you sure you want to delete this quote?",
              turbo_frame: "quotes"
            }, class: "btn btn-danger" %>
      </li>
    </ul>
  </section>
</main>

app/views/shared/_flash.html.erb
<% if flash[:notice] %>
    <div class="alert alert-success" role="alert">
        <%= flash[:notice] %>
    </div>
<% end %>

<% if flash[:alert] %>
    <div class="alert alert-danger" role="alert">
        <%= flash[:alert] %>
    </div>
<% end %>

app/views/shared/_form.html.erb
<%= form_with model: quote, class: "form" do |form| %>
  <div class="form-group">
    <%= form.label :title, class: "form-label" %>
    <%= form.text_field :title, class: "form-control" %>
    <% quote.errors.full_messages_for(:title).each do |message| %>
      <div class="text-danger"><%= message %></div>
    <% end %>
  </div>

  <div class="form-group">
    <%= form.label :body, class: "form-label" %>
    <%= form.text_area :body, class: "form-control", rows: 4 %>
    <% quote.errors.full_messages_for(:body).each do |message| %>
      <div class="text-danger"><%= message %></div>
    <% end %>
  </div>

  <div class="form-group">
    <%= form.submit "Submit", class: "btn btn-primary" %>
  </div>
<% end %>

app/views/shared/_navbar.html.erb
<nav class="navbar navbar-dark navbar-expand-lg bg-dark">
  <div class="container-fluid">
    <%= link_to 'DevNation', '#', class: 'navbar-brand' %>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarNavDropdown">
      <ul class="navbar-nav">
        <li class="nav-item">
          <%= link_to 'Home', home_path, class: 'nav-link active', 'aria-current': 'page' %>
        </li>
        <li class="nav-item">
          <%= link_to 'Quotes', quotes_path, class: 'nav-link' %>
        </li>
        <li class="nav-item">
          <%= link_to 'About Us', about_path, class: 'nav-link' %>
        </li>
        <li class="nav-item dropdown">
          <a class="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">
            More
          </a>
          <ul class="dropdown-menu">
            <li><a class="dropdown-item" href="#">Action</a></li>
            <li><a class="dropdown-item" href="#">Another action</a></li>
            <li><a class="dropdown-item" href="#">Something else here</a></li>
          </ul>
        </li>
      </ul>
    </div>
  </div>
</nav>

app/views/shared/_quote.html.erb
<div class="quote">
  <%= link_to quote.title, quote_path(quote) %>
  <div class="quote__actions">
    <%= button_to "Delete",
                  quote_path(quote),
                  method: :delete,
                  class: "btn btn--light" %>
    <%= link_to "Edit",
                edit_quote_path(quote),
                class: "btn btn--light" %>
  </div>
</div>